### ISSUE TITLE
No module named 'pyspedas/utilities.time_double'

### ISSUE THREAD

**Issue by Kurichi** [iugonet/pyudas#1]
In an environment with 'pyspedas>=1.5', the following error occurs:
```sh
$ python
>>> import iugonet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/project/.venv/lib/python3.12/site-packages/iugonet/__init__.py", line 1, in <module>
    from iugonet.ground.gmag_nipr import gmag_nipr
  File "/path/to/project/.venv/lib/python3.12/site-packages/iugonet/ground/gmag_nipr.py", line 3, in <module>
    from pyspedas.utilities.time_double import time_double
ModuleNotFoundError: No module named 'pyspedas.utilities.time_double'
```

This is likely due to a breaking change introduced in 'pyspedas>=1.5'. To fundamentally resolve the root cause, the import statement should be corrected as follows:
```python
from pyspedas import time_double
```

However, since there are numerous other breaking changes, a temporary solution would be to require 'pyspedas<1.5' in the `setup.py`.

**Comment by majomajo-fish** [comment]
Thank you for reporting the issue.
We have fixed the import part of all the codes that have this problem.

**Comment by Kurichi** [comment]
Thank you for the correction.
